name: user_repository
publish_to: none

environment:
  sdk: '>=2.19.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.7
  meta: ^1.9.1
  flutter_secure_storage: ^8.0.0
  fav_qs_api:
    path: ../fav_qs_api
  key_value_storage:
    path: ../key_value_storage
  domain_models:
    path: ../domain_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.0
  build_runner: ^2.3.3

